"""Fixed configuration for the final QDPT Dense-D768 Sandwich model."""

MODEL_NAME = "Qwen/Qwen3-VL-4B-Instruct"

TEXT_DIM = 2560
VISUAL_DIM = 1024
MAX_LENGTH = 2048

PRIVATE_TEXT_TOKENS = 20
TEXT_ANCHOR_TOKENS = 10
PRIVATE_VISUAL_TOKENS = 8
VISUAL_ANCHOR_TOKENS = 10

VISUAL_ANCHOR_LAYER = 17
WORKSPACE_DIM = 768
WORKSPACE_HEADS = 16

PROMPT_LEARNING_RATE = 0.3
VISUAL_PROMPT_LEARNING_RATE = 3e-5
QDPT_LEARNING_RATE = 1e-4

EPOCHS = 3
MICRO_BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 16
WARMUP_RATIO = 0.03
MAX_GRAD_NORM = 1.0
DATA_SEED = 42
DATALOADER_WORKERS = 2

MAX_NEW_TOKENS = 32
INSTRUCTION = "Answer with only a short answer."

EXPECTED_TRAINABLE_PARAMETERS = 7_805_184
ADAPTER_CONFIG_NAME = "dynamic_prompt_config.json"
ADAPTER_WEIGHTS_NAME = "dynamic_prompt.pt"

